mattermost/mattermost-plugin-boards

- server/api/api.go
From a cursory glance, when a real error occurs, we already log something at the application layer, so there's no reason to echo every api error response as an error log too. Errors should be actionable, but these logs were not, e.g.:
> access denied to templates
or:
> category ID specified in input does not exist for user
This PR duplicates https://github.com/mattermost/focalboard/pull/5022.
Fixes: https://mattermost.atlassian.net/browse/MM-59325
> stop logging errors for api error responses

- webapp/src/components/createBoardFromTemplate.tsx
MM-60440- fix styling when adding a new channel & board for different themes
https://mattermost.atlassian.net/browse/MM-60440
After:
https://github.com/user-attachments/assets/9263c0ab-fca8-428b-82ea-4d68bf23af7a
> MM-60440- fix styling when adding a new channel & board for different themes

- server/app/files.go
- server/services/store/sqlstore/blocks.go
https://hub.mattermost.com/icu/pl/qqb9tqrzdtfajyfrysd39ecaro
https://mattermost.atlassian.net/browse/MM-61043
> MM-61043 Error deleting board if fileID is empty

- server/services/store/sqlstore/board.go
There was an issue with boards where users in a channel couldn't access boards, even if the channel had the required permissions. This was because boards only checked for board membership and didn’t account for channel membership(This was done using `mattermostAuthLayer` previously which was removed and in refactoring we lost this code: https://github.com/mattermost-community/focalboard/blob/de5e5cc4141f14f69bf0e5666383997b81f851d6/server/services/store/mattermostauthlayer/mattermostauthlayer.go#L978). I added code to ensure that if a user is in a channel with access to boards, they can successfully access it.
Steps to Reproduce:
- Join Channel A, which has access to a board in version 8.0.0.
- As a member of Channel A, confirm you can access the board.
- Upgrade the board to version …
> MM-61109 fixed Error accessing board with added channels

- webapp/package.json
- webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
- webapp/src/components/cardDetail/__snapshots__/commentsList.test.tsx.snap
- webapp/src/components/cardDetail/cardDetail.test.tsx
- webapp/src/components/cardDetail/comment.test.tsx
- webapp/src/components/cardDetail/comment.tsx
- webapp/src/components/cardDetail/commentsList.test.tsx
- webapp/src/components/centerPanel.test.tsx
- webapp/src/store/teams.ts
- webapp/src/webapp_globals.ts
- webapp/tests/mock_window.tsx
- webapp/tests/setupFile.ts
- webapp/tsconfig.json
Added support to respect name display preference from channel to boards.
https://mattermost.atlassian.net/browse/MM-59373
> MM-59373: Respecting name display preference in boards

- server/services/store/sqlstore/board.go
This PR addresses a regression where channel members could not see boards linked to the channel in the channel's board RHS or the boards LHS. The issue occurred because boards only checked for board membership, which previously relied on `Mattermost's auth layer`. When the auth layer was removed during the plugin refactoring, the related code was lost.
- https://github.com/mattermost-community/focalboard/blob/de5e5cc4141f14f69bf0e5666383997b81f851d6/server/services/store/mattermostauthlayer/mattermostauthlayer.go#L1052
- https://github.com/mattermost-community/focalboard/blob/de5e5cc4141f14f69bf0e5666383997b81f851d6/server/services/store/mattermostauthlayer/mattermostauthlayer.go#L1101
This fix ensures channel members can now see linked boards in both the channel RHS and the boards LHS. …
> MM-61822 Fix the boards LHS and channel RHS boards channel memeber permission issue. 

- server/services/store/sqlstore/board.go
When adding individual members to the boards which were not part of the already linked boards was responded with 
`{error: "internal server error", "errorCode": 500}`. This was due to the server panicking if board members were not found. 
https://mattermost.atlassian.net/browse/MM-61945
> MM-61945: Able to add individual users to the boards

- webapp/src/components/cardDetail/__snapshots__/comment.test.tsx.snap
- webapp/src/components/cardDetail/__snapshots__/commentsList.test.tsx.snap
- webapp/src/components/cardDetail/comment.scss
- webapp/src/components/cardDetail/comment.tsx
- webapp/src/utils.ts
- webapp/src/webapp_globals.ts
Markdown in board card comments was not functioning as expected because the `formatText` function failed to set the `breaks` property to `true` in the markdown renderer. In the WebApp, this is handled by the CSS property `white-space: pre-wrap`, eliminating the need to explicitly set the `breaks` property. To resolve the issue, the same approach has been implemented in the boards plugin. Additionally, a custom link and table renderer, previously used in boards, has been reintroduced.
For more details: https://hub.mattermost.com/icu/pl/urix3jcxrfdmin63h5k3k6ab4y
https://mattermost.atlassian.net/browse/MM-61959
Before: 
After:
> Added linked and table renderer for markdown in comment

- webapp/src/components/sidebar/sidebar.test.tsx
- webapp/src/components/sidebar/sidebar.tsx
I was able to identify a way to reproduce this issue and pinpoint its root cause. This issue has been present for a long time, even before the pre-split.
Steps to Reproduce:
- Create a category in the board sidebar.
- Create a board within that category.
- Observe that there are now two categories in the sidebar: the one you created and the default `Boards` category.
- Switch to a different team.
- Switch back to the team where you created the category.
- Observe the issue: the board is either no longer in the created category or has been moved to the default `Boards` category.
Root Cause: This is a client-side issue caused by a [this](https://github.com/mattermost/mattermost-plugin-boards/blob/c95e6e871588ed8a2311c4266733ebf49b4b6b02/webapp/src/components/sidebar/sidebar.tsx#L127) …
> MM-62104 Fix board disappearing or move to default category when switching teams

- plugin.json
- server/manifest.go
- webapp/src/components/globalHeader/__snapshots__/globalHeader.test.tsx.snap
- webapp/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/src/constants.ts
Update board version to v9.0.4
> Update board version to 9.0.4

- webapp/src/components/cardDetail/comment.scss
- webapp/src/components/cardDetail/comment.tsx
- webapp/src/webapp_globals.ts
The card with links in the comments was not opening inside the boards. Error when opening the card with a link on the hub in the console: 
```bash
console.js:288 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' cdn.rudderlabs.com".
focalboard_9ce1515f8964ad29_bundle.js:2 [1734085501.12] error boundary redirecting to plugins/focalboard/error?id=unknown
```
This is because of the `Content-Security-Policy` Policy in webapp. This policy restricts the use of unsafe javascript methods like `new Functions()`, which can be exploited in injection attacks.
Before we were using the board markdown renderer which was working fine, but due to [Respect display name …
> Fix the comments link and markdown rendering issue

- .github/workflows/scorecards-analysis.yml
Adapt the scorecard-analysis workflow to match the one used by the [scorecard repository itself](https://github.com/ossf/scorecard/blob/v5.0.0/.github/workflows/scorecard-analysis.yml).
[Here](https://github.com/ossf/scorecard-action?tab=readme-ov-file#breaking-changes-in-v2) are the scorecard-action docs, mentioning which permissions should the job token have, if `publish_results: true` is used
> Migrate scorecard-analysis workflow to job token

- webapp/package-lock.json
- webapp/package.json
- webapp/src/index.tsx
- webapp/src/types/index.d.ts
Boards have their own navigation module that depends on the Desktop App to forward links between tabs. In version 5.11, the Desktop App removed the old `postMessage` code that enabled this functionality. Since Boards has not yet migrated to the new system, some links no longer work. To resolve this, board navigation has been updated to use the new Desktop A
https://mattermost.atlassian.net/browse/MM-61745
QA Steps: 
- Download and install the latest Mattermost Desktop nightly build: [v5.12.0-nightly.20250129](https://github.com/mattermost/desktop/releases/tag/5.12.0-nightly.20250129).
- Log in to Mattermost.
- Upload the boards built from the main branch.
- Attempt to open a card and navigate to other boards (navigation will not work).
- Build Boards from this branch.
- Repeat the same …
> MM-61745 Update Boards Navigation to Use the New Desktop API

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/lint-server.yml
As Ubuntu version 20.04 is no longer supported, I updated the Ubuntu version to the latest/22.04 to match the version of the webapp to run CI without error. 
https://github.com/actions/runner-images/issues/11101
https://mattermost.atlassian.net/browse/MM-64173
> Upgraded the Ubuntu version to 22.04

- webapp/src/csvExporter.ts
- webapp/src/properties/number/property.tsx
You can enter numbers with commas, for example, as thousand or decimal separators depending on your locale, into number-type columns. But when exporting to CSV, those values were being treated as numbers, which sometimes led to issues like `NaN` showing up or the values getting split across multiple columns. This change fixes that by treating the values as plain text during export, so they’re preserved exactly as entered.
https://mattermost.atlassian.net/browse/MM-63181
> MM-63181 Fix number formatting issue in Boards Plugin for CSV export

- webapp/src/store/cards.ts
A customer reported that search behaves differently depending on whether a card property is a `select` or `multiSelect` type.
For example:
- If a card has a `select` value of "single", typing "sing" or "ing" in the search bar correctly brings up that card.
- But if a card has a `multiSelect` value of "Banana", typing "ban" doesn’t return the card, only typing the full word "banana" works.
This feels inconsistent and confusing for users, especially since they expect both field types to support partial matches in the same way.
This PR fixes that by updating the `multiSelect` search logic to allow partial matching, just like `select` fields already do.
https://mattermost.atlassian.net/browse/MM-63598
> MM-63598 Fix unable to search for a portion of a word in a multiselect

- webapp/src/components/blockIconSelector.tsx
- webapp/src/components/boardIconSelector.tsx
- webapp/src/components/kanban/kanbanCard.tsx
- webapp/src/components/sidebar/sidebarBoardItem.tsx
- webapp/src/utils/emojiUtils.test.ts
- webapp/src/utils/emojiUtils.ts
Some emojis (for example, flag emojis) were not rendering properly on Windows systems due to platform-specific emoji support. To ensure consistent emoji rendering across platforms, I introduced a utility function `getValidEmojiData`, which wraps `emoji-mart`'s `getEmojiDataFromNative`. This allows us to retrieve normalised metadata for emojis and ensures we always use a valid native representation that the emoji-mart library can handle reliably.
https://mattermost.atlassian.net/browse/MM-63226
> Fix: Boards | Windows : Flag emojis not working on Windows

- webapp/src/components/calculations/calculations.ts
I wasn’t able to reproduce the original issue https://mattermost.atlassian.net/browse/MM-63231, but I added a check to handle cases where the code might return a `NaN` value.
https://mattermost.atlassian.net/browse/MM-63231
> Added check for NaN in kanban column header

- server/app/files.go
- server/app/files_test.go
- server/model/team.go
Global template initialisation failed after #108 due to overly strict validation in `getDestinationFilePath()` that rejected team ID "0" (`GlobalTeamID`).
`Error: "cannot initialise global templates for team 0: invalid team ID for team 0"`
Impact: Only 3 templates were imported instead of 13 on fresh installations
Modified `getDestinationFilePath()` to allow `GlobalTeamID` ("0") for template operations while maintaining validation for other use cases:
```go
if !mm_model.IsValidId(teamID) && !(isTemplate && teamID == model.GlobalTeamID) {
return "", fmt.Errorf("getDestinationFilePath: invalid team ID for teamID %s", teamID)
}
```
https://hub.mattermost.com/private-core/pl/fy98hhctff8fbf7ecnpx1qqcsa
https://mattermost.atlassian.net/browse/MM-64688
>  Fix for Global Template Initialisation

- server/model/board.go
- server/model/board_test.go
This PR fix the board unlinking issue with the channel. 
Problem: 
The issue was in the `BoardPatch.IsValid()` method in `server/model/board.go`. When unlinking a board from a channel, the API sends a patch with `ChannelID` set to an empty string "", but the validation logic wasn't handling this correctly. Updated the method to handle an empty `ChannelID`. 
https://mattermost.atlassian.net/browse/MM-64805
> Fix the unlinking issue of board to channel

- server/api/files.go
- server/app/files.go
- server/app/files_test.go
Adds validation to ensure files can only be accessed through their correct board and team context in file serving endpoints.
The file access endpoints (`/files/teams/{teamID}/{boardID}/{filename}` and `/files/teams/{teamID}/{boardID}/{filename}/info`) were not verifying that the requested file belonged to the specified board. This could lead to inconsistent behaviour when accessing files across different board contexts.
Added file ownership validation: New `ValidateFileOwnership()` function ensures files belong to the requested board and team
Dual validation approach:
For files with explicit `team/board` paths, validates the path structure
For files with newer storage format: validates that the file is referenced by blocks within the specified board
API-level protection: Added validation …
> Added file ownership validation to file access endpoints

- server/services/store/sqlstore/user.go
When searching for a person using both first name and last name in the person property on Boards, the user does not appear in the suggestions. This was because of the search condition 
```golang
Where(sq.Or{
sq.Like{"LOWER(u.username)": "%" + strings.ToLower(searchQuery) + "%"},
sq.Like{"LOWER(u.nickname)": "%" + strings.ToLower(searchQuery) + "%"},
sq.Like{"LOWER(u.firstname)": "%" + strings.ToLower(searchQuery) + "%"},
sq.Like{"LOWER(u.lastname)": "%" + strings.ToLower(searchQuery) + "%"},
})
```
When searching for "John Doe", no matches were found because the search term `john doe` doesn't exist in any single database field. 
Fix: We updated the query to also include a `fullNamefield` that concatenates the first and last name (based on the database type), allowing us to match against …
> Fix the Firstname and Lastname together search in person property

- webapp/src/styles/main.scss
This pull request changes the `user-select` value for `.focalboard-body *` from `none` to `text`. With this change, users are able to select and copy comments (either whole or parts of it). This is a functionality our Mattermost and Boards users request repeatedly because they have to be able to copy parts of comments for further usage (e.g., phone numbers or ticket/incident numbers; in our case, they are really long).
I couldn't think of any situation in which the current setting would be useful, but maybe I am missing something. Is there a reason that this was set to `none`?
\-
> CSS: Allow to select and copy comments in a card

- server/api/auth.go
Public board sharing stopped working after v9.0.0 when the standalone and plugin parts were split. Users accessing shared boards with read tokens receive 401 Unauthorised errors.
In v9.0.0, the attachSession function was incorrectly modified to reject all anonymous users, breaking the intended design where:
`sessionRequired`: Requires authentication
`attachSession`: Allows anonymous users with valid read tokens
Restore anonymous access fallback in `attachSession` by allowing requests without `Mattermost-User-Id` header to proceed to individual handlers, which properly validate read tokens.
Before: Anonymous requests → 401 Unauthorised
After: Anonymous requests → Handler validates read token → Allow/Deny appropriately
https://mattermost.atlassian.net/browse/MM-65017
> Fix: Public sharing board functionality broken in v9.0.0
